### PR TITLE
QA suggestions

### LINKED ISSUE #290: Suggestions
On the staking screen when depositing collateral, the warning should read: "You will be able to withdraw your collateral balance at any time, except for any that is locked on a scheduled proposal."
Screenshot 2021-03-12 at 15 11 56

This proposal is cancelled yet I can still stake on it. #17 for reference. If I try to stake it fails. Presumably we don't need to let the user explicitly unstake because anything in cancelled proposals should be take into account on the UI? In which case can we remove the support button in this situation?
Screenshot 2021-03-12 at 15 25 44

No table entry added to the stake screen for the previously cancelled proposal. The available Honey has updated but there's no indication as to why. Turns out I need to refresh and reconnect my wallet before it updates.
Screenshot 2021-03-12 at 15 35 00

The warning on the right for a suggestion should read: "The suggestion will exist until it is challenged or removed."
Screenshot 2021-03-12 at 15 50 46

Can we remove the ` at the start of the error message at the bottom.
Screenshot 2021-03-11 at 13 53 41

"remaining" should be "remainder".
Screenshot 2021-03-11 at 13 58 31

When challenging an action this needs to be laid out better. 
The action collateral message should remove the "Your wallet balance is 18 HNY."
The dispute fees message should remove the "This balance will be returned to your account if the submitter accepts your settlement offer or if you win the dispute raised to Celeste."
The dispute fees warning should say "lock" instead of "pay".
There should be an info box at the bottom saying "The action collateral and dispute fees will be returned to your account if the submitter accepts your settlement offer or if you win the dispute raised to Celeste. Your wallet balance is 18 HNY."
Screenshot 2021-03-12 at 16 10 56

Should read "This proposal has been challenged but you can continue to support it to increase conviction. When the challenge is resolved, if allowed, the proposal will be resumed otherwise this proposal will be cancelled."
Screenshot 2021-03-12 at 16 27 15

This should read "If you specify the proposal amount in DAI it will be converted to HNY at the time of execution."
Screenshot 2021-03-12 at 16 41 37

The links to the proposal from the staking manager don't work for me. They just go to home.

The modals disappear regularly. I've noticed if I click in the modal and remove the click after dragging the mouse outside of it, it will disappear. Can this be prevented? Of course clicking outside should still close it.

Also the modals don't disappear after a transaction has been processed, you have to click them away. I think they should close automatically.

The links to celeste are broken because it uses "questions" in the URL instead of "disputes".

I've noticed when depositing in the staking manager my transaction sometimes fails because the gas limit is set too low. Can it default to a higher value? Tx: https://rinkeby.etherscan.io/tx/0xf94d4f4b10e38eb5d42a9e18cd9a9688072e7a6f9f8b91c1855f6e321686d881

### PR DESCRIPTION
**Pull request by rperez89**
This closes #290 

Still need to address the modal one that will suggested but need to give a thought to it

### CODE REVIEW

File: src/screens/Home.js [hunk 1]
```diff
@@ -145,6 +145,7 @@ const Home = React.memo(function Home() {
           <MultiModal
             visible={createProposalModalVisible}
             onClose={() => setCreateProposalModalVisible(false)}
+            onClosed={() => setCreateProposalModalVisible(false)}
```
Comment (fabriziovigevani) [inline src/screens/Home.js:148]: Is this necessary? Seems that is doing the same as `onClose` which will be fired first?

File: src/components/ProposalDetail/ProposalActions.js [hunk 2]
```diff
@@ -77,12 +80,15 @@ function ProposalActions({
...
-      disabled: !accountBalance.gt(0),
+    if (mode === 'support') {
+      return {
+        text: 'Support this proposal',
+        action: onRequestSupportProposal,
+        mode: 'strong',
+        disabled: !accountBalance.gt(0),
+      }
     }
+    return null
```
Comment (fabriziovigevani) [inline src/components/ProposalDetail/ProposalActions.js:91]: Should we place it at the top to avoid all the if statements?

```suggestion
   if(!mode) {
     return null
   }
```

**Review by fabriziovigevani — COMMENTED** [review]
Awesome Ro!

Some comments


> Still need to address the modal one that will suggested but need to give a thought to it
If we end up closing the issue #290, let's create a new one with this pending task

**Review by fabriziovigevani — APPROVED** [review]
Awesome!
