### PR TITLE
Withdraw collateral fix

### LINKED ISSUE #452: Collateral Manager: withdraw multimodal should not display the `Create proposal` button
Screen Shot 2021-05-22 at 2 56 30 PM

### PR DESCRIPTION
**Pull request by rperez89**
Don't show create proposal button on withdraw.

this closes #452

### CODE REVIEW

File: src/components/Garden/ModalFlows/StakeScreens/StakeScreens.js [hunk 1]
```diff
@@ -24,15 +24,17 @@ function StakeScreens({ mode, stakeManagement, stakeActions }) {
...
+    if (mode === 'deposit') {
+      return (
+        <Button
+          label="Create proposal"
+          mode="strong"
+          onClick={handleCreateProposal}
+          wide
+        />
+      )
+    }
```
Comment (fabriziovigevani) [inline src/components/Garden/ModalFlows/StakeScreens/StakeScreens.js:36]: Let's return `null` in any other case

**Review by fabriziovigevani — COMMENTED** [review]
One small comment and LGTM
