### PR TITLE
Fixes

### LINKED ISSUE #447: `Create proposal` button is not popping up modal
After signing covenant, depositing collateral, the `Create proposal` button redirects to the garden home page but doesn't pop up the Proposal creation modal

### LINKED ISSUE #448: Challenge action:  Approve token amounts on necessary tokens
When challenging a proposal, it asumes colateral Requirement token and disputeFee token is the same. Which is not true for gardens other than 1Hive.

### LINKED ISSUE #450: Challenge proposal: when using BYOT the token logic is not correct
When handling the Challenge action the logic should consider if the Garden has a `WrappableToken` and in that case use that on as the OGT instead. Now we are considering the OGT but the balances displayed are for the GDN token.

Screen Shot 2021-05-22 at 3 06 00 PM

In the following picture, I have OGT balances and anyways the modal show me I don't.

Screen Shot 2021-05-22 at 3 04 51 PM

### PR DESCRIPTION
**Pull request by fabriziovigevani**
closes #448 , closes #450, closes #447

- Fixes create proposal modal not popping when being redirected from collateral manager
- Challenge actions: 2 Approves (one for collateral amount, one for dispute fee amount) since collateral token and dispute fee token can be different. If tokens are the same, then one approve for the added amount.
- useDisputeFees: Returns amount converted in BN so that components don't need to handle this.   
- Challenge requirements: Uses dispute fee token data and account balance (previously using collateral token data)
- Raise Dispute requirements: Uses dispute fee token data and account balance (previously using collateral token data)

### CODE REVIEW

File: src/components/Garden/Home.js [hunk 1]
```diff
@@ -77,6 +70,15 @@ const Home = React.memo(function Home() {
     handleShowModal('unwrap')
   }, [handleShowModal])
 
+  useEffect(() => {
+    console.log('running')
```
Comment (rperez89) [inline src/components/Garden/Home.js:74]: let's remove this console log

File: src/components/Garden/Home.js [hunk 2]
```diff
@@ -77,6 +70,15 @@ const Home = React.memo(function Home() {
...
+    // Components that redirect to create a proposal will do so through "garden/${gardenId}/create" url
+    if (account && history.location.pathname.includes('create')) {
+      console.log('entered')
```
Comment (rperez89) [inline src/components/Garden/Home.js:77]: also this one

File: src/components/Garden/ModalFlows/ChallengeProposalScreens/ChallengeProposalScreens.js [hunk 3]
```diff
@@ -7,51 +7,68 @@ import { useDisputeFees } from '@hooks/useDispute'
 import { useAgreement } from '@hooks/useAgreement'
 import BigNumber from '@lib/bigNumber'
 import { toDecimals } from '@utils/math-utils'
+import { addressesEqual } from '@1hive/connect-core'
```
Comment (rperez89) [inline src/components/Garden/ModalFlows/ChallengeProposalScreens/ChallengeProposalScreens.js:10]: for consistency let's use or the one in utils or the one on the 1hive-ui

File: src/components/Garden/ModalFlows/ChallengeProposalScreens/ChallengeProposalScreens.js [hunk 4]
```diff
@@ -7,51 +7,68 @@ import { useDisputeFees } from '@hooks/useDispute'
...
+  const getTransactions = useCallback(
+    async (
+      onComplete,
+      actionId,
+      settlementOffer,
+      challengerFinishedEvidence,
+      context
+    ) => {
+      const collateralToken = proposal.collateralRequirement.tokenId
+      const collateralAmount = proposal.collateralRequirement.challengeAmount
```
Comment (rperez89) [inline src/components/Garden/ModalFlows/ChallengeProposalScreens/ChallengeProposalScreens.js:56]:
```suggestion
      const {challengeAmount: collateralAmount, tokenId: collateralToken} = proposal.collateralRequirement
```

File: src/components/Garden/ModalFlows/ChallengeProposalScreens/ChallengeProposalScreens.js [hunk 5]
```diff
@@ -7,51 +7,68 @@ import { useDisputeFees } from '@hooks/useDispute'
...
+
+      const disputeFeeToken = disputeFees.token
+      const disputeFeeAmount = disputeFees.amount
```
Comment (rperez89) [inline src/components/Garden/ModalFlows/ChallengeProposalScreens/ChallengeProposalScreens.js:59]:
```suggestion
      const {amount: disputeFeeAmount, token: disputeFeeToken}  = disputeFees
```

File: src/components/Garden/ModalFlows/ChallengeProposalScreens/ChallengeProposalScreens.js [hunk 6]
```diff
@@ -71,7 +93,7 @@ function ChallengeProposalScreens({ agreementActions, proposal }) {
         content: (
           <ChallengeRequirements
             agreement={agreement}
-            accountBalance={token.accountBalance}
+            accountBalance={(wrappableToken || token).accountBalance}
```
Comment (rperez89) [inline src/components/Garden/ModalFlows/ChallengeProposalScreens/ChallengeProposalScreens.js]: let's create a collateralToken var outside

**Review by rperez89 — COMMENTED** [review]
looks good! some comments

File: src/components/Garden/ActionCollateral.js [hunk 7]
```diff
@@ -15,12 +15,12 @@ function ActionCollateral({ proposal }) {
       `}
     >
       <img
-        src={honeyIconSvg}
+        src={getTokenIconBySymbol(collateralRequirement.tokenSymbol)} // TODO: Use deefault-token-list
```
[the remark this answers is not in the document]
Comment (fabriziovigevani) [reply src/components/Garden/ActionCollateral.js:18]: I think that's fine though since it would just show the default token icon. I don't have strong feelings with keeping it this way or using the `default-token-list` but i think thos way we don't maintain duplicated metadata.

Nevertheless it should be noted that if we go with our current implementation we will need to update this function (`getTokenIconBySymbol `), since it just returns the icon from a mapping of harcoded symbol to icon, it's not a general solution.

File: src/components/Garden/ModalFlows/ChallengeProposalScreens/ChallengeProposalScreens.js (hunk 4 above)
Comment (fabriziovigevani) [reply src/components/Garden/ModalFlows/ChallengeProposalScreens/ChallengeProposalScreens.js:56]: In this case i would prefer to keep is as since the suggested code takes 4 lines when auto-linted

File: src/components/Garden/ActionCollateral.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (rperez89) [reply src/components/Garden/ActionCollateral.js]: > maintain duplicated

yeah in any case we can fetch it from the default token list and fallback to the dao list in case not found it
